### ISSUE TITLE
sml-garden/message-constructor can't be found

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta-machine-learning#62]
When running sml_garden.fbp with sol-flow.json

./sml_garden.fbp:71:30 Couldn't resolve type 'sml-garden/message-constructor' of node 'SmlMessageConstructorFuzzy'

sml-garden.so was installed in correct path

**Comment by cabelitos** [comment]
Hello, unfortunately this a problem related to Soletta and not SML itself. 
This happens because the message-constructor node can not find symbols that should be exported by Soletta's flower power node.

However, we have a workaround for this problem. When building Soletta, be sure you check the flower-power node as built-in. Doing like this, the message constructor will be able to find the symbols and everyone will be happy.

We will try to fix this problem ASAP.
