### ISSUE TITLE
Problem with example

### ISSUE THREAD

**Issue by nirmalsinghania2008** [solettaproject/soletta-machine-learning#68]
```
inputs = sml_get_input_list(sml);
sensor = sml_variables_list_index(sml, inputs, 0);
sml_variable_set_value(sml, sensor, sensor_state);

outputs = sml_get_output_list(sml);
light = sml_variables_list_index(sml, outputs, 0);
```

  *\*  sml_variable_set_value(sml, light, switch_state);**

```
return true;
```

}

static void
output_state_changed_cb(struct sml_object *sml,
    struct sml_variables_list *changed, void *data)
{
    struct sml_variable *light;
    double prediction;

```
light = sml_variables_list_index(sml, changed, 0);
```

  *\*  prediction = sml_variable_get_value(sml, light);**

```
/* When SML can't predict a value, it'll be set to NaN */
if (isnan(prediction)) {
    printf("Sorry, can't predict light state.\n");
    return;
}

/* prediction is equal to current state */
```

*\*    if ((prediction > 0.5) == switch_state) {**
        return;
    }

```
if (prediction > 0.5) {
    printf("Light should be turned ON.\n");
} else {
    printf("Light should be turned OFF.\n");
}
```

}

I think there is some problem in this.
we are setting light=switch_state in sml_variable_set_value(sml, light, switch_state)
then in prediction we are getting the light state  prediction = sml_variable_get_value(sml, light)
an then we are checking   if ((prediction > 0.5) == switch_state)

how the prediction working?
isn't it setting a value and getting same value?
correct me if i am wrong

**Comment by otaviobp** [comment]
read_state_cb is the callback called by SML to read current state of inputs and outputs. Inputs and outputs set in this callback are used to train the ml algorithm and inputs are used to predict a new value of the output.

output_state_changed_cb is called when sml predicts a new value of output, that is different from value read in read_state_cb. We are not getting the same value we set in read_state_cb because SML has changed the variable value.

As sml variables are double variables, we may have calls to output_state_changed_cb with predictions that won't really change the light status. For example, if light was 0.8 and prediction is 0.9, output_state_changed_cb will be called, but we won't need to change light status, because 0.8 and 0.9 is mapped, by this sample, to ON. That's the reason we have this check: if ((prediction > 0.5) == switch_state)

The samples looks correct to me, but I didn't test that. If you are having unexpected results, let us know.

**Comment by nirmalsinghania2008** [comment]
the sample program was having case errors and datatype errors,
so i modified the wiki as asked by iscaro.
I am also thinking of creating documentation for other sample program(Air conditioner,Foosball score) in sml as there are small issues we can consider compiling every sample program(including -lm,-std=c99 flags and changing $PATH,$LD_LIBRARY_PATH based on the system)
what you think?
Thank you for your answer.

**Comment by nirmalsinghania2008** [comment]
one more question,how sml is knowing that it has to predict the value at some time?
it is not predicting value at every point for process loop but just specific points.

to quote "sml_set_output_state_changed_callback
This callback will be called when SML makes a prediction for at least one output variable"
how do we know that it is called?
 in other words,at what point of program sml makes a prediction?

**Comment by otaviobp** [comment]
We have talked about that question in IRC, if I am not mistaken. I'll close the issue, but If you need any other information about this problem, talk to me or @cabelitos at IRC or send an email to the ml.
